# ***Assignment 1 - Working with NumPy***

In [47]:
# Importing NumPy.
import numpy as np

## 1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.  


In [48]:
# Creating a 1D Array with integers from 1 to 20.
arr_1d = np.arange(21)
print("1D Array :", arr_1d)

1D Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [49]:
# a. Calculate the sum, mean, median, and standard deviation of the elements in the 1D Array.

sum = np.sum(arr_1d)
print(f"Sum of elements of 1D Array :", sum)
mean = np.mean(arr_1d)
print(f"Mean of elements of 1D Array :", mean)
median = np.median(arr_1d)
print(f"Median of elements of 1D Array :", median)
std_dev = np.round(np.std(arr_1d),2)
print(f"Standard Deviation of elements of 1D Array :", std_dev)

Sum of elements of 1D Array : 210
Mean of elements of 1D Array : 10.0
Median of elements of 1D Array : 10.0
Standard Deviation of elements of 1D Array : 6.06


In [50]:
# b. Find the indices of elements greater than 10 in the 1D Array.
grt_than_10 = np.where(arr_1d > 10)
grt_than_10

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),)

## 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.


In [51]:
# Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.
arr_2d = (np.arange(1,17)).reshape(4,4)

# a. Print the 2D Array.
print("2D Array :\n", arr_2d)

2D Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [52]:
# b. Find the transpose of the array
trnsps_arr_2d = np.transpose(arr_2d)
print("Transposed 2D Array :\n", trnsps_arr_2d)

Transposed 2D Array :
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [53]:
# c. Calculate the row-wise and column-wise sums of the array.
row_wise_sum = np.sum(arr_2d, axis=1)
print("Row-wise Sum :", row_wise_sum)

column_wise_sum = np.sum(arr_2d, axis=0)
print("Column-wise Sum :", column_wise_sum)

Row-wise Sum : [10 26 42 58]
Column-wise Sum : [28 32 36 40]


## 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.


In [54]:
# Create two 3 X 3 arrays filled with random integers between 1 and 20.
A = np.random.randint(1, 21, size=(3, 3))
B = np.random.randint(1, 21, size=(3, 3))

print("Array A:\n", A)
print("Array B:\n", B)


Array A:
 [[14 18  4]
 [10 16 17]
 [16 11  6]]
Array B:
 [[13  5  6]
 [ 6 20 13]
 [19 17  4]]


In [55]:
# a. Element-wise operations
print("\nElement-wise Addition:\n", A + B)
print("\nElement-wise Subtraction:\n", A - B)
print("\nElement-wise Multiplication:\n", A * B)



Element-wise Addition:
 [[27 23 10]
 [16 36 30]
 [35 28 10]]

Element-wise Subtraction:
 [[ 1 13 -2]
 [ 4 -4  4]
 [-3 -6  2]]

Element-wise Multiplication:
 [[182  90  24]
 [ 60 320 221]
 [304 187  24]]


In [56]:
# b. Compute the dot product of the two arrays.
dot_product = np.dot(A, B)
print("\nDot Product:\n", dot_product)


Dot Product:
 [[366 498 334]
 [549 659 336]
 [388 402 263]]


## 4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

In [57]:
# Create 1D array of size 12
arr_1d = np.arange(1, 13)   # [1, 2, 3, ..., 12]
print("1D Array:\n", arr_1d)

# Reshape into 3x4 array
arr_2d = arr_1d.reshape(3, 4)
print("2D Array:\n", arr_2d)

# Slice: first two rows, last two columns
sliced = arr_2d[:2, -2:]
print("\nSliced Array:\n", sliced)


1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array:
 [[3 4]
 [7 8]]
